# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: master_mapper.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='master_mapper.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13master_mapper.proto\"\x1d\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\"6\n\tDataPoint\x12\x13\n\x0b\x63\x65ntroid_id\x18\x01 \x01(\x05\x12\t\n\x01x\x18\x02 \x01(\x01\x12\t\n\x01y\x18\x03 \x01(\x01\"e\n\nMapRequest\x12\x13\n\x0bstart_index\x18\x01 \x03(\x05\x12\x11\n\tend_index\x18\x02 \x03(\x05\x12\x14\n\x0cnum_reducers\x18\x03 \x01(\x05\x12\x19\n\tcentroids\x18\x04 \x03(\x0b\x32\x06.Point\"\x1e\n\x0bMapResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\'\n\x11ReturnDataRequest\x12\x12\n\nreducer_id\x18\x01 \x01(\x05\"5\n\x12ReturnDataResponse\x12\x1f\n\x0b\x64\x61ta_points\x18\x01 \x03(\x0b\x32\n.DataPoint\"(\n\x12StartReduceRequest\x12\x12\n\nmapper_ids\x18\x01 \x03(\x05\"&\n\x13StartReduceResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x65\n\x06Mapper\x12\"\n\x03Map\x12\x0b.MapRequest\x1a\x0c.MapResponse\"\x00\x12\x37\n\nReturnData\x12\x12.ReturnDataRequest\x1a\x13.ReturnDataResponse\"\x00\x32\x45\n\x07Reducer\x12:\n\x0bStartReduce\x12\x13.StartReduceRequest\x1a\x14.StartReduceResponse\"\x00\x62\x06proto3'
)




_POINT = _descriptor.Descriptor(
  name='Point',
  full_name='Point',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='Point.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='Point.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=52,
)


_DATAPOINT = _descriptor.Descriptor(
  name='DataPoint',
  full_name='DataPoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='centroid_id', full_name='DataPoint.centroid_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='x', full_name='DataPoint.x', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='DataPoint.y', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=108,
)


_MAPREQUEST = _descriptor.Descriptor(
  name='MapRequest',
  full_name='MapRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='start_index', full_name='MapRequest.start_index', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='end_index', full_name='MapRequest.end_index', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_reducers', full_name='MapRequest.num_reducers', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='centroids', full_name='MapRequest.centroids', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=211,
)


_MAPRESPONSE = _descriptor.Descriptor(
  name='MapResponse',
  full_name='MapResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='MapResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=213,
  serialized_end=243,
)


_RETURNDATAREQUEST = _descriptor.Descriptor(
  name='ReturnDataRequest',
  full_name='ReturnDataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='reducer_id', full_name='ReturnDataRequest.reducer_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=245,
  serialized_end=284,
)


_RETURNDATARESPONSE = _descriptor.Descriptor(
  name='ReturnDataResponse',
  full_name='ReturnDataResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data_points', full_name='ReturnDataResponse.data_points', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=286,
  serialized_end=339,
)


_STARTREDUCEREQUEST = _descriptor.Descriptor(
  name='StartReduceRequest',
  full_name='StartReduceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='mapper_ids', full_name='StartReduceRequest.mapper_ids', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=341,
  serialized_end=381,
)


_STARTREDUCERESPONSE = _descriptor.Descriptor(
  name='StartReduceResponse',
  full_name='StartReduceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='StartReduceResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=383,
  serialized_end=421,
)

_MAPREQUEST.fields_by_name['centroids'].message_type = _POINT
_RETURNDATARESPONSE.fields_by_name['data_points'].message_type = _DATAPOINT
DESCRIPTOR.message_types_by_name['Point'] = _POINT
DESCRIPTOR.message_types_by_name['DataPoint'] = _DATAPOINT
DESCRIPTOR.message_types_by_name['MapRequest'] = _MAPREQUEST
DESCRIPTOR.message_types_by_name['MapResponse'] = _MAPRESPONSE
DESCRIPTOR.message_types_by_name['ReturnDataRequest'] = _RETURNDATAREQUEST
DESCRIPTOR.message_types_by_name['ReturnDataResponse'] = _RETURNDATARESPONSE
DESCRIPTOR.message_types_by_name['StartReduceRequest'] = _STARTREDUCEREQUEST
DESCRIPTOR.message_types_by_name['StartReduceResponse'] = _STARTREDUCERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Point = _reflection.GeneratedProtocolMessageType('Point', (_message.Message,), {
  'DESCRIPTOR' : _POINT,
  '__module__' : 'master_mapper_pb2'
  # @@protoc_insertion_point(class_scope:Point)
  })
_sym_db.RegisterMessage(Point)

DataPoint = _reflection.GeneratedProtocolMessageType('DataPoint', (_message.Message,), {
  'DESCRIPTOR' : _DATAPOINT,
  '__module__' : 'master_mapper_pb2'
  # @@protoc_insertion_point(class_scope:DataPoint)
  })
_sym_db.RegisterMessage(DataPoint)

MapRequest = _reflection.GeneratedProtocolMessageType('MapRequest', (_message.Message,), {
  'DESCRIPTOR' : _MAPREQUEST,
  '__module__' : 'master_mapper_pb2'
  # @@protoc_insertion_point(class_scope:MapRequest)
  })
_sym_db.RegisterMessage(MapRequest)

MapResponse = _reflection.GeneratedProtocolMessageType('MapResponse', (_message.Message,), {
  'DESCRIPTOR' : _MAPRESPONSE,
  '__module__' : 'master_mapper_pb2'
  # @@protoc_insertion_point(class_scope:MapResponse)
  })
_sym_db.RegisterMessage(MapResponse)

ReturnDataRequest = _reflection.GeneratedProtocolMessageType('ReturnDataRequest', (_message.Message,), {
  'DESCRIPTOR' : _RETURNDATAREQUEST,
  '__module__' : 'master_mapper_pb2'
  # @@protoc_insertion_point(class_scope:ReturnDataRequest)
  })
_sym_db.RegisterMessage(ReturnDataRequest)

ReturnDataResponse = _reflection.GeneratedProtocolMessageType('ReturnDataResponse', (_message.Message,), {
  'DESCRIPTOR' : _RETURNDATARESPONSE,
  '__module__' : 'master_mapper_pb2'
  # @@protoc_insertion_point(class_scope:ReturnDataResponse)
  })
_sym_db.RegisterMessage(ReturnDataResponse)

StartReduceRequest = _reflection.GeneratedProtocolMessageType('StartReduceRequest', (_message.Message,), {
  'DESCRIPTOR' : _STARTREDUCEREQUEST,
  '__module__' : 'master_mapper_pb2'
  # @@protoc_insertion_point(class_scope:StartReduceRequest)
  })
_sym_db.RegisterMessage(StartReduceRequest)

StartReduceResponse = _reflection.GeneratedProtocolMessageType('StartReduceResponse', (_message.Message,), {
  'DESCRIPTOR' : _STARTREDUCERESPONSE,
  '__module__' : 'master_mapper_pb2'
  # @@protoc_insertion_point(class_scope:StartReduceResponse)
  })
_sym_db.RegisterMessage(StartReduceResponse)



_MAPPER = _descriptor.ServiceDescriptor(
  name='Mapper',
  full_name='Mapper',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=423,
  serialized_end=524,
  methods=[
  _descriptor.MethodDescriptor(
    name='Map',
    full_name='Mapper.Map',
    index=0,
    containing_service=None,
    input_type=_MAPREQUEST,
    output_type=_MAPRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ReturnData',
    full_name='Mapper.ReturnData',
    index=1,
    containing_service=None,
    input_type=_RETURNDATAREQUEST,
    output_type=_RETURNDATARESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MAPPER)

DESCRIPTOR.services_by_name['Mapper'] = _MAPPER


_REDUCER = _descriptor.ServiceDescriptor(
  name='Reducer',
  full_name='Reducer',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=526,
  serialized_end=595,
  methods=[
  _descriptor.MethodDescriptor(
    name='StartReduce',
    full_name='Reducer.StartReduce',
    index=0,
    containing_service=None,
    input_type=_STARTREDUCEREQUEST,
    output_type=_STARTREDUCERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_REDUCER)

DESCRIPTOR.services_by_name['Reducer'] = _REDUCER

# @@protoc_insertion_point(module_scope)
