# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: master_reducer.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14master_reducer.proto\"#\n\rReduceRequest\x12\x12\n\nreducer_id\x18\x01 \x01(\x05\"=\n\x0eReduceResponse\x12+\n\x11updated_centroids\x18\x01 \x03(\x0b\x32\x10.UpdatedCentroid\"6\n\x0fUpdatedCentroid\x12\x13\n\x0b\x63\x65ntroid_id\x18\x01 \x01(\x05\x12\x0e\n\x06values\x18\x02 \x03(\x02\x32\x36\n\x07Reducer\x12+\n\x06Reduce\x12\x0e.ReduceRequest\x1a\x0f.ReduceResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'master_reducer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REDUCEREQUEST']._serialized_start=24
  _globals['_REDUCEREQUEST']._serialized_end=59
  _globals['_REDUCERESPONSE']._serialized_start=61
  _globals['_REDUCERESPONSE']._serialized_end=122
  _globals['_UPDATEDCENTROID']._serialized_start=124
  _globals['_UPDATEDCENTROID']._serialized_end=178
  _globals['_REDUCER']._serialized_start=180
  _globals['_REDUCER']._serialized_end=234
# @@protoc_insertion_point(module_scope)
