# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import reducer_mapper_pb2 as reducer__mapper__pb2


class ReducerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReceivePartition = channel.unary_unary(
                '/reducer_mapper.Reducer/ReceivePartition',
                request_serializer=reducer__mapper__pb2.PartitionRequest.SerializeToString,
                response_deserializer=reducer__mapper__pb2.EmptyResponse.FromString,
                )


class ReducerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReceivePartition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReducerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReceivePartition': grpc.unary_unary_rpc_method_handler(
                    servicer.ReceivePartition,
                    request_deserializer=reducer__mapper__pb2.PartitionRequest.FromString,
                    response_serializer=reducer__mapper__pb2.EmptyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'reducer_mapper.Reducer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Reducer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReceivePartition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/reducer_mapper.Reducer/ReceivePartition',
            reducer__mapper__pb2.PartitionRequest.SerializeToString,
            reducer__mapper__pb2.EmptyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
